apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wlq5w2knj-go
  janus-idp.io/tekton: wlq5w2knj-go
  backstage.io/kubernetes-id: wlq5w2knj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wlq5w2knj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
